driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 4096

provisioner:
  name: chef_zero
  product_name: chef
  product_version: latest
  channel: current

platforms:
  - name: centos-6
    run_list: yum-epel::default
  - name: centos-7
    run_list: yum-epel::default
  - name: debian-8
    run_list: apt::default
  - name: freebsd-10
    run_list: freebsd::portsnap
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-16.04
    run_list: apt::default
  #
  # The following (private) boxes are shared via Atlas. Please note this
  # requires adding your Atlas account to the `Chef` org and will
  # require a `vagrant login`.
  #
  # The Mac OS X boxes are VMware only also. You can enable VMware Fusion
  # as the default provider by copying `.kitchen.local.yml.vmware.example`
  # over to `.kitchen.local.yml`.
  #
  - name: macosx-10.10
    driver:
      box: chef/macosx-10.10 # private
  - name: macosx-10.11
    driver:
      box: chef/macosx-10.11 # private
  # By adding an `i386` to the name `OMNIBUS_WINDOWS_ARCH` will be
  # configured correctly to force Omnibus to 32-bit build mode.
  - name: windows-server-2012r2-standard-i386
    driver:
      box: chef/windows-server-2012r2-standard # private
  - name: windows-server-2012r2-standard
    driver:
      box: chef/windows-server-2012r2-standard # private
  - name: windows-server-2016-standard
    driver:
      box: chef/windows-server-2016-standard # private

suites:
  - name: default
    run_list: omnibus::default

  #
  # Build
  #
  - name: omnibus_build_execute
    run_list: omnibus_build::execute
